files updated

diff --git a/.github/workflows/selenium-tests.yml b/.github/workflows/selenium-tests.yml
--- a/.github/workflows/selenium-tests.yml
+++ b/.github/workflows/selenium-tests.yml
@@ -30,12 +30,25 @@ jobs:
       - name: Debug - List Allure Results
         run: Get-ChildItem -Recurse target/allure-results
 
+      - name: Confirm allure-results exists
+        run: |
+          if (Test-Path "target/allure-results") {
+            echo "✅ Allure results found!"
+          } else {
+            echo "❌ Allure results missing"
+            exit 1
+          }
+        shell: pwsh
+
+
       - name: Generate Allure Report
         run: |
           mvn io.qameta.allure:allure-maven:2.11.2:report ^
             -Dallure.results.directory=target/allure-results ^
-            -Dallure.report.directory=target/allure-report
+            -Dallure.report.directory=allure-report
+        working-directory: ${{ github.workspace }}
         shell: cmd
+
 
 
       - name: Debug - Show Allure Report
